# Generated by Django 5.2 on 2025-04-06 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forwarding_rules', '0001_initial'),
    ]

    operations = [
    ]
