# Generated by Django 5.2 on 2025-04-06 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoForwarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('forwarding_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('disposition', models.CharField(blank=True, max_length=50, null=True)),
                ('has_forwarding_filters', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('investigation_note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Auto Forwarding Rule',
                'verbose_name_plural': 'Auto Forwarding Rules',
                'db_table': 'autoforwarding',
            },
        ),
        migrations.CreateModel(
            name='ForwardingFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.JSONField(help_text='Filter criteria (e.g. from, subject)')),
                ('action', models.JSONField(help_text='Actions to take (e.g. forward, addLabels)')),
                ('created_at', models.CharField(blank=True, max_length=50, null=True)),
                ('forwarding', models.OneToOneField(db_column='forwarding_id', on_delete=django.db.models.deletion.CASCADE, related_name='filter', to='forwarding_rules.autoforwarding')),
            ],
            options={
                'verbose_name': 'Forwarding Filter',
                'verbose_name_plural': 'Forwarding Filters',
                'db_table': 'forwardingfilter',
            },
        ),
    ]
