version: '3.8'

# This Docker Compose file defines services for the Email Forwarding Rules Audit application
# NOTE: This service requires a .env file with proper configuration
# See the README.md file for instructions on setting up environment variables

services:
  # Redis service for message broker
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Celery worker service
  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    volumes:
      - ./:/app
      - reports_data:/app/reports
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis

  # Django web service (optional - can be started separately)
  web:
    build:
      context: .
      dockerfile: Dockerfile.celery  # Reuse the same Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
      - reports_data:/app/reports
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis

volumes:
  redis_data:
  reports_data: 